---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    reviewers:
      - ne-sachirou
    assignees:
      - ne-sachirou
    ignore:
      - dependency-name: black
        versions:
          - 21.4b0
          - 21.4b1
      - dependency-name: flake8
        versions:
          - 3.9.0
      - dependency-name: yamllint
        versions:
          - 1.26.0
      - dependency-name: mypy
        versions:
          - "0.800"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: webpack
        versions:
          - 5.18.0
          - 5.19.0
          - 5.20.0
          - 5.20.1
          - 5.20.2
          - 5.21.2
          - 5.22.0
          - 5.23.0
          - 5.24.0
          - 5.24.1
          - 5.24.2
          - 5.24.3
          - 5.24.4
          - 5.25.1
          - 5.26.0
          - 5.26.2
          - 5.26.3
          - 5.27.1
          - 5.27.2
          - 5.28.0
          - 5.30.0
          - 5.31.0
          - 5.31.2
          - 5.32.0
          - 5.33.2
          - 5.34.0
          - 5.35.0
          - 5.35.1
          - 5.36.0
      - dependency-name: npm-check-updates
        versions:
          - 11.1.1
          - 11.1.10
          - 11.1.4
          - 11.1.8
          - 11.1.9
          - 11.2.0
          - 11.2.1
          - 11.2.2
          - 11.3.0
          - 11.4.1
          - 11.5.1
          - 11.5.3
      - dependency-name: webpack-cli
        versions:
          - 4.4.0
          - 4.5.0
