---
name: deploy

"on":
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "17"
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "16"
      - name: Install pipenv
        run: pip install --user pipenv
      - uses: actions/setup-python@v2
        with:
          cache: pipenv
          python-version: "3.10"
      - name: Setup
        run: |
          npm ci
          sudo apt-get install -y --no-install-recommends curl
          curl -fsSL https://www.antlr.org/download/antlr-4.9-complete.jar > ~/antlr-4.jar
      - name: Build
        run: |
          rm -fv docs/main.js* sifaru_yusin/DekuRule*.js sifaru_yusin/*.interp sifaru_yusin/*.tokens
          (cd sifaru_yusin && java -cp ~/antlr-4.jar:$CLASSPATH org.antlr.v4.Tool -Dlanguage=JavaScript DekuRule.g4)
          pipenv run npx webpack --config webpack.prod.js
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
