---
name: test

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "16"
      - name: Install pipenv
        run: pip install --user pipenv
      - uses: actions/setup-python@v2
        with:
          cache: pipenv
          python-version: "3.10"
      - name: Setup
        run: |
          pipenv sync -d --pre
          npm ci
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
      - name: Test
        run: |
          #pipenv check
          #npm audit
          #git ls-files | grep -E '\.y(a?)ml$' | xargs -t pipenv run yamllint
          #pipenv run black --check main.py sifaru_yusin
          #pipenv run flake8 main.py sifaru_yusin
          #pipenv run mypy main.py || true
          pipenv run python tasks.py test
