---
name: test

"on":
  pull_request: { }
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache Python
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-
      - name: Setup
        run: |
          pip install --user pipenv
          pipenv sync -d --pre
          npm ci
      - name: Test
        run: |
          pipenv check
          npm audit
          git ls-files | grep -E '\.y(a?)ml$' | xargs -t pipenv run yamllint
          pipenv run black --check main.py sifaru_yusin
          pipenv run flake8 main.py sifaru_yusin
          pipenv run mypy main.py || true
